### ISSUE TITLE
Replace `BasicSubsystem` with `GenericSubsystem` and `LambdaSubsystem`

### ISSUE THREAD

**Issue by ScarletMetal** [Spikes-2212-Programming-Guild/SpikesLib#125]
In order to make our code more extendable and readable we should add an abstract class named `GenericSubsystem` to replace `BasicSubsystem` as the parent class for all of our subsystems. and add a `LambdaSubsystem` class which extends it and uses lambdas.

**Comment by Spikes-2212** [comment]
Right now this issue will be closed, it will be reopened after a complete design for SL is planned.
